[package]
name = "mp-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mp-core = { workspace = true }
anyhow = { workspace = true }
pulldown-cmark = { workspace = true }
ratatui = "0.28"
crossterm = "0.28"
unicode-width = "0.1"
color-eyre = "0.6"
