name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: NixOS/nix-installer-action@0dd8719406e061e029989ec91b93d677d9e2bd63 # main 2026-02-15
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
      - name: Create draft release
        run: nix develop -c goreleaser release --clean --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
